# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Project/PROF/3_dac_adc_triggered_read/vivado_project_bit/vivado_project_bit.srcs/sources_1/ip/cordic_0/cordic_0.xci
# IP: The module: 'cordic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Project/PROF/3_dac_adc_triggered_read/vivado_project_bit/vivado_project_bit.gen/sources_1/ip/cordic_0/cordic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Project/PROF/3_dac_adc_triggered_read/vivado_project_bit/vivado_project_bit.srcs/sources_1/ip/cordic_0/cordic_0.xci
# IP: The module: 'cordic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Project/PROF/3_dac_adc_triggered_read/vivado_project_bit/vivado_project_bit.gen/sources_1/ip/cordic_0/cordic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
