# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Projects/2023/Single_Tx_Rx_System/3_dac_adc_triggered_read/gateware/xem7320-ltc2264-12.xdc

# IP: C:/Projects/2023/Single_Tx_Rx_System/3_dac_adc_triggered_read/gateware/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: C:/Projects/2023/Single_Tx_Rx_System/3_dac_adc_triggered_read/gateware/ip/enc_clk/enc_clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==enc_clk || ORIG_REF_NAME==enc_clk} -quiet] -quiet
